# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 792d379c750f134d5097ada5f6e769c46a7b891488b91a38e77d50e58daa33078fec44224f27cb4a6d0aa6c7448768e2373624196a765ac77d2eb9f0941d2696

test:
  secret_key_base: ffe8b14973e6aca38fecd359784d0b17a77c3e16b9b9bf172ff472a9d468419405119e8d4f100d1f452a7c35dfa9c492005d015c8556630c4f7c4ef4852aba2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
