# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: febc327167d5d89bf5b5cc024a3bec1904134dc1f1c4ca21785c90c9413a91fa73f1666f05b19e4273af9347aeaae55ade621c2b17ca4fe463cf7f4b20b7d22f

test:
  secret_key_base: 9ecacb297620e49463e564f44a680d9cb27c72f073c00bd0bfe787820e233a52439682ca7d56e68fd118c7f9010648d0b612ce49604fbea74de03eb069632146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
